language: ruby

sudo: false # explicitly use container-based architecture

branches:
  only:
    - master

cache: bundler
bundler_args: --without development # --path=~/.bundle

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc" # skip installing docs for gems

services:
  - postgresql

addons:
  postgresql: "11.1"

before_script:
  - "psql -c 'create database rodrouter_test;' -U postgres"
  - bin/rails db:migrate RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bundle exec codeclimate-test-reporter
