version: "3.4"

x-default: &default
  build: .
  depends_on:
    - db
  environment:
    - DATABASE_URL=postgres://postgres@db:5432
  networks:
    - web
  volumes:
    - bundle:/bundle
    - .:/app

services:
  web:
    <<: *default
    ports:
      - "3000:3000"

  db:
    image: postgres:12.1-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - web
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh

networks:
  web:

volumes:
  bundle:
  pgdata:
