version: "3.3"
services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - web
    volumes:
      - bundle_cache:/bundle_cache
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:11.1-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=123abc
    networks:
      - web
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

networks:
  web:

volumes:
  bundle_cache:
  pgdata:
