default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: rodrouter_development

test:
  <<: *default
  database: rodrouter_test

production:
  <<: *default
  database: rodrouter_production
