default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: cartographer_development

test:
  <<: *default
  database: cartographer_test

production:
  <<: *default
  database: cartographer_production
